### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by ivanfig** [zhemao/rmem-server#17]
I want to use [Sourcegraph](https://sourcegraph.com) for rmem-server code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/zhemao/rmem-server. (It should only take 30 seconds.)

Thank you!

**Comment by jcarreira** [comment]
Hopefully it works now.

Please reopen the ticket if it still does not work.
